server:
  port: 8761

eureka:
  instance:
    hostname: registry-discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://registry-discovery:${server.port}/eureka/


spring:
  cloud:
    config:
      discovery:
        enabled: true
