server:
  port: 63002

management:
  endpoints:
    web:
      exposure:
        include: info, health, shutdown
  endpoint:
    shutdown:
      enabled: true


---
spring:
  profiles:
    active: default
eureka:
  instance:
    hostname: registry-discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/

---
spring:
  profiles:
    active: qa-zone-a
eureka:
  instance:
    hostname: qa-peer1
  client:
    serviceUrl:
      defaultZone: http://qa-peer2:${server.port}/eureka/

---
spring:
  profiles:
    active: qa-zone-b
eureka:
  instance:
    hostname: qa-peer2
  client:
    serviceUrl:
      defaultZone: http://qa-peer1:${server.port}/eureka/
