server:
  port: 63002

management:
  endpoints:
    web:
      exposure:
        include: info, health, shutdown
  endpoint:
    shutdown:
      enabled: true

logging:
  config: classpath:logback.xml

---
spring:
  profiles:
    active: default
eureka:
  instance:
    hostname: registry-discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
